name: brew test-bot
on:
  push:
    branches: [main]
  pull_request:
defaults:
  run:
    shell: /bin/zsh -Negku {0}
jobs:
  test-bot:
    strategy:
      matrix:
        include:
        - runner: macos-26
        - runner: macos-26-intel
    runs-on: ${{matrix.runner}}
    permissions:
      actions: read
      checks: read
      contents: read
      pull-requests: read
    steps:
    - name: Obtain .xcode-version
      uses: actions/checkout@v6
      with:
        repository: mas-cli/mas
        sparse-checkout: .xcode-version
        sparse-checkout-cone-mode: false

    - name: Select Xcode version
      run: xcodes select

    - name: Set up Homebrew
      id: set-up-homebrew
      uses: Homebrew/actions/setup-homebrew@main
      with:
        token: ${{secrets.GITHUB_TOKEN}}

    - name: Cache Homebrew Bundler RubyGems
      uses: actions/cache@v5
      with:
        path: ${{steps.set-up-homebrew.outputs.gems-path}}
        key: ${{matrix.runner}}-rubygems-${{steps.set-up-homebrew.outputs.gems-hash}}
        restore-keys: ${{matrix.runner}}-rubygems-

    - run: brew test-bot --only-cleanup-before

    - run: brew test-bot --only-setup

    - run: brew test-bot --only-tap-syntax

    - name: Build, test & modify bottle to be for oldest macOS version supported by the current platform
      if: github.event_name == 'pull_request'
      run: |
        brew test-bot --only-formulae
        autoload zmv
        zmv '(*)tahoe(*)' '$1ventura$2'
        [[ -n *ventura.bottle.json(#qN) ]] && sed -i '' s/tahoe/ventura/g *ventura.bottle.json || true

    - name: Upload bottles as artifact
      if: always() && github.event_name == 'pull_request'
      uses: actions/upload-artifact@v6
      with:
        name: bottles_${{matrix.runner}}
        path: '*.bottle.*'
